"use client";
import Link from "next/link";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    try {
      const routes = ["/checkouts", "/equipment-checkin", "/inventory", "/chain-of-custody", "/reports", "/access-control", "/business-integration"];
      routes.forEach((r) => fetch("/api" + r).catch(() => {}));
    } catch (e: any) {
      setError(e.message || "Failed to initialize");
    }
  }, []);

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 to-blue-900 text-white p-8">
      <div className="max-w-4xl mx-auto">
        {error && (
          <div className="mb-6 bg-red-500/20 border border-red-400/30 text-red-100 p-4 rounded-lg flex items-center justify-between">
            <span>{error}</span>
            <button onClick={() => setError(null)} className="ml-4 text-red-200 hover:text-white font-bold">✕</button>
          </div>
        )}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">Troop 719 Inventory Tracking </h1>
          <p className="text-xl text-blue-200">AI-Generated Production System</p>
        </div>
        <div className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Features</h2>
          <div className="grid md:grid-cols-2 gap-4">
            <Link href="/checkouts" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Checkouts</h3>
              <p className="text-blue-200 text-sm">Navigate to /checkouts</p>
            </Link>
            <Link href="/equipment-checkin" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Equipment checkin</h3>
              <p className="text-blue-200 text-sm">Navigate to /equipment-checkin</p>
            </Link>
            <Link href="/inventory" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Inventory</h3>
              <p className="text-blue-200 text-sm">Navigate to /inventory</p>
            </Link>
            <Link href="/chain-of-custody" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Chain of custody</h3>
              <p className="text-blue-200 text-sm">Navigate to /chain-of-custody</p>
            </Link>
            <Link href="/reports" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Reports</h3>
              <p className="text-blue-200 text-sm">Navigate to /reports</p>
            </Link>
            <Link href="/access-control" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Access control</h3>
              <p className="text-blue-200 text-sm">Navigate to /access-control</p>
            </Link>
            <Link href="/business-integration" className="block bg-white/10 hover:bg-white/20 transition rounded-xl p-6">
              <h3 className="text-xl font-semibold mb-2">Business integration</h3>
              <p className="text-blue-200 text-sm">Navigate to /business-integration</p>
            </Link>
          </div>
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">System Overview</h2>
            <p className="text-blue-100">This system was automatically generated by Dev AI from a Business Requirements Document (BRD).</p>
          </div>
          <div className="bg-white/10 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">Built With</h2>
            <ul className="text-blue-100 space-y-2">
              <li>Next.js 14</li>
              <li>TypeScript</li>
              <li>Tailwind CSS</li>
              <li>Supabase (Database)</li>
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
